-- MySQL Script generated by MySQL Workbench
-- Thu Mar 10 22:23:43 2016
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema staff
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema staff
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `staff` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `staff` ;

-- -----------------------------------------------------
-- Table `staff`.`manage`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `staff`.`manage` (
  `emp_id` VARCHAR(15) NULL DEFAULT NULL,
  PRIMARY KEY (`emp_id`),
  CONSTRAINT `fk_manage_emp1`
    FOREIGN KEY (`emp_id`)
    REFERENCES `staff`.`emp` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `staff`.`departement`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `staff`.`departement` (
  `id` INT(11) NOT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `manage_emp_id` VARCHAR(15) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_departement_manage1_idx` (`manage_emp_id` ASC),
  CONSTRAINT `fk_departement_manage1`
    FOREIGN KEY (`manage_emp_id`)
    REFERENCES `staff`.`manage` (`emp_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `staff`.`workfor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `staff`.`workfor` (
  `departement_id` INT(11) NULL,
  `start_date` DATE NULL,
  INDEX `fk_workfor_departement1_idx` (`departement_id` ASC),
  PRIMARY KEY (`departement_id`),
  CONSTRAINT `fk_workfor_departement1`
    FOREIGN KEY (`departement_id`)
    REFERENCES `staff`.`departement` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `staff`.`emp`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `staff`.`emp` (
  `id` VARCHAR(15) NOT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `gender` CHAR(1) NULL DEFAULT NULL,
  `start_job` DATE NULL DEFAULT NULL,
  `warm_contract` TINYINT(1) NULL,
  `warm_date` DATE NULL DEFAULT NULL,
  `citizen_id` VARCHAR(19) NULL DEFAULT NULL,
  `jamsostek_id` VARCHAR(45) NULL DEFAULT NULL,
  `bank_account` VARCHAR(45) NULL DEFAULT NULL,
  `npwp` VARCHAR(45) NULL DEFAULT NULL,
  `email` VARCHAR(45) NOT NULL,
  `non_aktif` TINYINT(1) NOT NULL,
  `photoprofile` LONGBLOB NULL,
  `workfor_departement_id` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_emp_workfor1_idx` (`workfor_departement_id` ASC),
  CONSTRAINT `fk_emp_workfor1`
    FOREIGN KEY (`workfor_departement_id`)
    REFERENCES `staff`.`workfor` (`departement_id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `staff`.`attendance`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `staff`.`attendance` (
  `date_job` DATE NOT NULL,
  `emp_id` VARCHAR(15) NOT NULL,
  `h_in` TIME NULL DEFAULT NULL,
  `h_out` TIME NULL DEFAULT NULL,
  `dt_in` DATETIME NULL DEFAULT NULL,
  `dt_out` DATETIME NULL DEFAULT NULL,
  PRIMARY KEY (`date_job`, `emp_id`),
  INDEX `fk_attendance_emp1_idx` (`emp_id` ASC),
  CONSTRAINT `fk_attendance_emp1`
    FOREIGN KEY (`emp_id`)
    REFERENCES `staff`.`emp` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `staff`.`branch`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `staff`.`branch` (
  `id` INT(3) NOT NULL,
  `namebrach` VARCHAR(45) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = latin1
COLLATE = latin1_swedish_ci;


-- -----------------------------------------------------
-- Table `staff`.`card`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `staff`.`card` (
  `id` INT(11) NOT NULL,
  `emp_id` VARCHAR(15) NOT NULL,
  `date_create` DATE NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `id_UNIQUE` (`id` ASC),
  INDEX `fk_card_emp1_idx` (`emp_id` ASC),
  CONSTRAINT `fk_card_emp1`
    FOREIGN KEY (`emp_id`)
    REFERENCES `staff`.`emp` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `staff`.`dayoff`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `staff`.`dayoff` (
  `id` DATE NOT NULL,
  `period_id` INT(11) NOT NULL,
  `name` VARCHAR(45) NULL DEFAULT NULL,
  `describe_off` TEXT NULL DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_dayoff_periode1_idx` (`period_id` ASC))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `staff`.`engineatt`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `staff`.`engineatt` (
  `pin` INT(11) NOT NULL,
  `dateatt` DATETIME NOT NULL,
  `verified` INT(11) NULL DEFAULT NULL,
  `status` INT(11) NULL DEFAULT NULL,
  PRIMARY KEY (`pin`, `dateatt`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `staff`.`officetime`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `staff`.`officetime` (
  `id` INT(11) NOT NULL,
  `name_time` VARCHAR(32) NULL DEFAULT NULL,
  `must_in` TIME NULL DEFAULT NULL,
  `must_out` TIME NULL DEFAULT NULL,
  `limit_in_start` TIME NULL DEFAULT NULL,
  `limit_in_last` TIME NULL DEFAULT NULL,
  `limit_out_start` TIME NULL DEFAULT NULL,
  `limit_out_last` TIME NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `staff`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `staff`.`user` (
  `id` INT(11) NOT NULL,
  `user_name` VARCHAR(45) NULL DEFAULT NULL,
  `user_password` VARCHAR(45) NULL DEFAULT NULL,
  `user_level` TINYINT(4) NULL DEFAULT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8;


-- -----------------------------------------------------
-- Table `staff`.`gaji`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `staff`.`gaji` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `emp_id` VARCHAR(15) NOT NULL,
  `tgl` DATE NULL,
  `gp` DECIMAL(10,2) NULL,
  `tmasakerja` DECIMAL(10,2) NULL,
  `tjabatan` DECIMAL(10,2) NULL,
  `tfungsional` DECIMAL(10,2) NULL,
  `tallowance` DECIMAL(10,2) NULL,
  `tpremihadir` DECIMAL(10,2) NULL,
  `laukpauk` DECIMAL(10,2) NULL,
  `tdapen` DECIMAL(10,2) NULL,
  `tinsentif` DECIMAL(10,2) NULL,
  `gajiplus` DECIMAL(10,2) NULL,
  `gajiminus` DECIMAL(10,2) NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_gaji_emp1_idx` (`emp_id` ASC),
  CONSTRAINT `fk_gaji_emp1`
    FOREIGN KEY (`emp_id`)
    REFERENCES `staff`.`emp` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `staff`.`groupcabang`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `staff`.`groupcabang` (
  `emp_id` VARCHAR(15) NOT NULL,
  `branch_id` INT(3) NOT NULL,
  PRIMARY KEY (`emp_id`, `branch_id`),
  INDEX `fk_emp_has_branch_branch1_idx` (`branch_id` ASC),
  INDEX `fk_emp_has_branch_emp1_idx` (`emp_id` ASC),
  CONSTRAINT `fk_emp_has_branch_emp1`
    FOREIGN KEY (`emp_id`)
    REFERENCES `staff`.`emp` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_emp_has_branch_branch1`
    FOREIGN KEY (`branch_id`)
    REFERENCES `staff`.`branch` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `staff`.`periodetahun`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `staff`.`periodetahun` (
  `id` YEAR NOT NULL,
  `dscription` VARCHAR(45) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `staff`.`periodebulan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `staff`.`periodebulan` (
  `id` INT NOT NULL,
  `startdate` DATE NULL,
  `enddate` DATE NULL,
  `periodetahun_id` YEAR NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `fk_periodebulan_periodetahun1_idx` (`periodetahun_id` ASC),
  CONSTRAINT `fk_periodebulan_periodetahun1`
    FOREIGN KEY (`periodetahun_id`)
    REFERENCES `staff`.`periodetahun` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `staff`.`officetimeemp`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `staff`.`officetimeemp` (
  `officetime_id` INT(11) NOT NULL,
  `emp_id` VARCHAR(15) NOT NULL,
  INDEX `fk_officetime_has_emp_emp1_idx` (`emp_id` ASC),
  INDEX `fk_officetime_has_emp_officetime1_idx` (`officetime_id` ASC),
  PRIMARY KEY (`emp_id`, `officetime_id`),
  CONSTRAINT `fk_officetime_has_emp_officetime1`
    FOREIGN KEY (`officetime_id`)
    REFERENCES `staff`.`officetime` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_officetime_has_emp_emp1`
    FOREIGN KEY (`emp_id`)
    REFERENCES `staff`.`emp` (`id`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
